---
# MonoRepo multi services

version: "3.8"
services:
  rproxy:
    image: ${REGISTRY_URI:-public.ecr.aws/johnpreston/}blog-rproxy:${IMAGE_TAG:-latest}
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DEBUG: "true"
      LOGLEVEL: DEBUG

  app01:
    image: ${REGISTRY_URI:-public.ecr.aws/johnpreston/}blog-app01:${IMAGE_TAG:-latest}
    build:
      context: ./app01
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: ".5"
        reservations:
          memory: 128MB
          cpus: "0.25"
    ports:
    - 5000
    healthcheck: &supervisord_healthcheck
      test:
        - CMD-SHELL
        - supervisorctl -c supervisord.config status
      retries: 3
      interval: 10s
      timeout: 5s


  app02:
    image: ${REGISTRY_URI:-public.ecr.aws/johnpreston/}blog-app02:${IMAGE_TAG:-latest}
    build:
      context: ./app02
#      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: ".5"
        reservations:
          memory: 128MB
          cpus: "0.25"
    ports:
    - 5000
    healthcheck:
      <<: *supervisord_healthcheck

  app03:
    image: ${REGISTRY_URI:-public.ecr.aws/johnpreston/}blog-app02:${IMAGE_TAG:-latest}
    build:
      context: ./app02
#      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: ".5"
        reservations:
          memory: 128MB
          cpus: "0.25"
    ports:
    - 5000
    healthcheck:
      <<: *supervisord_healthcheck
